import React from "react";
export { ReactComponent as start } from "../../icons/Notification/start.svg";
export { ReactComponent as close } from "../../icons/Notification/close.svg";
// export { ReactComponent as delete } from "../../icons/Notification/delete.svg";
export { ReactComponent as save } from "../../icons/Notification/save.svg";
export { ReactComponent as create } from "../../icons/Notification/create.svg";
export { ReactComponent as error } from "../../icons/Notification/error.svg";
export { ReactComponent as success } from "../../icons/Notification/success.svg";
export { ReactComponent as edit } from "../../icons/edit.svg";
export { ReactComponent as copy } from "../../icons/copy.svg";
